apiVersion: v1
kind: Pod
metadata:
  labels:
    name: attachmentmanager
spec:
  serviceAccountName: jenkins
  containers:
  - name: maven
    image: "maven:3.8.3-openjdk-17"
    imagePullPolicy: Always
    command:
    - cat
    tty: true
